# recv_streams: 16
# total_nfft: 16777216 # Nfft or Fre channels
Debug: true
# don't make the memory pool size > 128GB
Memory_pool_per_stream: 8 # GB
observation_mode: 1 # 观测模式 0 : baseband 1: spcetrum
cal_mode: true
# blanking  time 10ms before and after
# cal_on_t: 5 # on time
# cal_off_t: 5 # off time
integration_t: 1 # Intergration time s
#
win_bw: 256e6 # window bandwidth hz 1e6,2e6,4e6,32e6,64e6
win_channels: 65536 # window channels  32768,65536
Storage_node_ip: 192.168.101.3
Storage_node_mac: 0c:42:a1:78:84:e4
Sender_Nic: ens81f0v0
# disk1
Baseband_Folder0: /data
# disk2
Baseband_Folder1: /data1
subband_monitor: true
subbands:
  # recv port from FPGA is  60000,60001
  # send to master node port from 60000
  #  subband 0

  - gpu_id: 0
    enable: true
    start_freq: 384e6
    end_freq: 640e6
    port: 60000
    windows:
      - center_freq: 512e6
    # - center_freq: 2201e6
    # - center_freq: 2202e6
    # - center_freq: 2203e6

  # recv port from FPGA is  60002,60003
  - gpu_id: 0
    enable: true
    start_freq: 640e6
    end_freq: 896e6
    port: 60001
    windows:
      - center_freq: 768e6
    # - center_freq: 2501e6
    # - center_freq: 2502e6
    # - center_freq: 2503e6

  - gpu_id: 1
    enable: true
    start_freq: 896e6
    end_freq: 1152e6
    port: 60002
    windows:
      - center_freq: 1024e6

  - gpu_id: 1
    enable: true
    start_freq: 1152e6
    end_freq: 1408e6
    port: 60003
    windows:
      - center_freq: 1280e6

  - gpu_id: 2
    enable: false
    start_freq: 0
    end_freq: 256e6

  - gpu_id: 2
    enable: false
    start_freq: 0
    end_freq: 256e6

  - gpu_id: 3
    enable: false
    start_freq: 0
    end_freq: 256e6

  - gpu_id: 3
    enable: false
    start_freq: 0
    end_freq: 256e6
